title: Trobança
description: (Tro-ban-tsa) Encuentra varios recursos en galaicoportugués medieval, aprende el idioma usado por los trovadores en toda España cristiana y consigue acceso a una gran cantidad de obras literarias de la edad media.
theme: just-the-docs

url: https://trobanza.github.io

# Set a path/url to a logo that will be displayed instead of the title
logo: "/elementos/imagenes/marcatrobanza/sanvalentintrobanza.png"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/elementos/imagenes/marcatrobanza/favicon.ico"

# Color de sitio
color_scheme: papelviejo

defaults:
  -
    scope:
      path: "texto"
    values:
      layout: "default"
